---
title: "testing world map network"
author: "Wenyu Zeng"
date: "2020/2/13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, warning = FALSE)
```

```{r}
rm(list = ls())
library(dplyr)
library(network)
library(maps)
library(scales)
library(igraph)
```

```{r, echo=FALSE}
# # nodes come from the above table and contain geo-coordinates for some
# # randomly picked countries
# node <- read.csv("D:/Download/Countries.csv", header = T, as.is = T)
# #So we now have 15 countries, each with an ID, geo-coordinates (lon and lat) and a name. These are our graph nodes. We’ll now create some random connections (edges) between our nodes:
# 
# edges <- read.csv("D:/Download/George Washington University/Spring 2020/Network Data Science/EdgeList.csv", header = T, as.is = T)
# 
# names(edges)[1] <- "to"
# names(edges)[2] <- "from"
# 
# onode <- read.csv("D:/Download/George Washington University/Spring 2020/Network Data Science/CountryNodes.csv")
# 
# node <- node %>% right_join(onode, by = "Country") %>% mutate(ID = row_number()) %>% mutate(Country = as.factor(Country))
# 
# nodec <- na.omit(node)
# 
# #%>% mutate(ID = row_number())
# 
# head(node)
# head(edges)
# 
# # N_EDGES_PER_NODE_MIN <- 1
# # N_EDGES_PER_NODE_MAX <- 4
# # N_CATEGORIES <- 4
# # 
# # # edges: create random connections between countries (nodes)
# # edges <- map_dfr(nodes$id, function(id) {
# #   n <- floor(runif(1, N_EDGES_PER_NODE_MIN, N_EDGES_PER_NODE_MAX+1))
# #   to <- sample(1:max(nodes$id), n, replace = FALSE)
# #   to <- to[to != id]
# #   categories <- sample(1:N_CATEGORIES, length(to), replace = TRUE)
# #   weights <- runif(length(to))
# #   data_frame(from = id, to = to, weight = weights, category = categories)
# # })
# 
# # edges <- edges %>% mutate(category = as.factor(category))
# ```
# 
# ```{r}
# nrow(node); length(unique(node$id))
# nrow(edges); nrow(unique(edges[,c("from", "to")]))
# ```
# 
# ```{r}
# reducedEdgelist2<-edges[edges$Weight>500000, c("from", "to", "Weight")]
# head(reducedEdgelist2) 
# nrow(reducedEdgelist2)
# ```
# 
# ```{r}
# set.seed(123)
# coocNet2<-network(reducedEdgelist2,
#                  matrix.type='edgelist',
#                  directed=FALSE,  # this will be an undirected network
#                  ignore.eval=FALSE,  # confusingly, this tells it to include edge weights
#                  names.eval='Weight'  # names for the edge weights
#                  )
```

```{r}
cinf <- read.csv("ChinaFluNetReport.csv")
kinf <- read.csv("KoreaFluNetReport.csv")
iinf <- read.csv("ItalyFluNetReport.csv")
jinf <- read.csv("JapanFluNetReport.csv")
#rinf <- read.csv("IranFluNetReport.csv")
```

```{r}
names(cinf)[1] <- "Country"
names(kinf)[1] <- "Country"
names(iinf)[1] <- "Country"
names(jinf)[1] <- "Country"
```
```{r}
cinf2019 <- cinf %>% select("Country", "Year", "ALL_INF") %>% filter(Year == 2019) 
#%>% summarise("yr_total" = sum("All_INF"))
sum(cinf2019$ALL_INF)

```

```{r}
kinf2019 <- kinf %>% select("Country", "Year", "ALL_INF") %>% filter(Year == 2019) 
#%>% summarise("yr_total" = sum("All_INF"))
kinf2019 <- na.omit(kinf2019)
sum(kinf2019$ALL_INF)

```

```{r}
iinf2019 <- iinf %>% select("Country", "Year", "ALL_INF") %>% filter(Year == 2019) 
#%>% summarise("yr_total" = sum("All_INF"))
iinf2019 <- na.omit(iinf2019)
sum(iinf2019$ALL_INF)
```

```{r}
jinf2019 <- jinf %>% select("Country", "Year", "ALL_INF") %>% filter(Year == 2019) 
#%>% summarise("yr_total" = sum("All_INF"))
jinf2019 <- na.omit(jinf2019)
sum(jinf2019$ALL_INF)
```

```{r}
inf2019 <- matrix(c("China", 122757,"Republic of Korea", 271,"Italy", 6361,"Japan",9525),ncol=2,byrow=TRUE)
colnames(inf2019) <- c("Country", "cases")
rownames(inf2019) <- c("1","2","3", "4")
inf2019 <- as.table(inf2019)
inf19 <- as.data.frame.matrix(inf2019, header = T)
```

```{r}
mnode <- read.csv("CountryNodes.csv", header = T, as.is=T)
medge <- read.csv("EdgeList.csv", header = T, as.is = T)
medge15 <- read.csv("EdgeList2015.csv", header = T, as.is = T)
```

```{r}
names(medge)[3] <- "Weight19"
medge$Weight15 <- medge15$Weight
```

```{r}
medge$Weight <- (medge$Weight19 - medge$Weight15)/medge$Weight15
```

```{r}
medgef <- medge %>% filter(Destination == c("China", "Italy", "Japan", "Republic of Korea", "United States of America")) %>%
  #filter(Origin == c("China", "Italy", "Japan", "Dem. People's Republic of Korea")) %>%
  filter(Weight > 0)
medgef <- medgef[c("Origin", "Destination", "Weight19", "Weight15", "Weight")]
```

```{r}
fullinfu <- read.csv("CountryNodes_Influenza232_updated.csv", header = T, as.is = T)
```

```{r}
mnodeup <- fullinfu %>% select("Country", "UN_Region", "Influenza2019")
selectedcoun <- medgef %>% select("Origin")
a <- c("China", "United States of America", "Italy")
#b <- as.character.default(selectedcoun)
#gsub("\\", "", b)
```

```{r}
mnodeup2 <- mnodeup[mnodeup$Country %in% medgef$Origin, ]
```


```{r}
mnodeup <- fullinfu %>% select("Country", "UN_Region", "Influenza2019") %>% filter()
  # filter(Country %in% c("China", "Italy", "Japan", "Republic of Korea","Australia", "China, Hong Kong SAR",
  #                                       "Russian Federation", "Sri Lanka", "Thailand",
  #                                       "United States of America", "Algeria", "Belarus",
  #                                       "Bosnia and Herzegovina", "Brunei Darussalam", "Cabo Verde",
  #                                       "Chile", "Colombia", "Costa Rica",
  #                                       "Democratic Republic of the Congo","Dominican Republic",
  #                                       "Equatorial Guinea", "Ethiopia", "Finland", "Gabon", "Ghana",
  #                                       "Grenada", "Guinea", "India", "Ireland", "Latvia", "Libya",
  #                                       "Madagascar", "Mali", "Mauritania", "Namibia", "Nigeria",
  #                                       "Norway", "Philippines", "Romania", "Saint Kitts and Nevis",
  #                                       "Samoa", "Senegal", "Singapore", "Solomon Islands", "Spain",
  #                                       "Suriname", "Tajikistan", "Turkey", "Uganda",
  #                                       "United Republic of Tanzania", "Uzbekistan", "Zimbabwe",
  #                                       "Canada", "Germany", "Mexico", "Netherlands", "Peru",
  #                                       "United Kingdom", "Viet Nam", "Cambodia", "France", "Indonesia",
  #                                       "Armenia", "Behamas", "Belgium", "Bolivia", "Denmark", "Egypt",
  #                                       "Gambia", "Greece", "Guatemala", "Israel", "Kazakhstan", 
  #                                       "Lao People's Democratic Republic", "Marshall Islands", "Montserrat",
  #                                       "Nicaragua", "Panama", "Poland", "Republic of Moldova", "Serbia",
  #                                       "Trinidad and Tobago", "Venezuela (Bolivarian Republic of)","Zambia",
  #                                       "Bolivia (Plurinational State of)", "Benin", "Bangladesh", "Bulgaria"
  #                                       ))
```








```{r}
mnodef <- mnode %>% filter(Country %in% c("China", "Italy", "Japan", "Republic of Korea", 
                                        "Australia", "China, Hong Kong SAR",
                                        "Russian Federation", "Sri Lanka", "Thailand",
                                        "United States of America", "Algeria", "Belarus",
                                        "Bosnia and Herzegovina", "Brunei Darussalam", "Cabo Verde",
                                        "Chile", "Colombia", "Costa Rica",
                                        "Democratic Republic of the Congo","Dominican Republic",
                                        "Equatorial Guinea", "Ethiopia", "Finland", "Gabon", "Ghana",
                                        "Grenada", "Guinea", "India", "Ireland", "Latvia", "Libya",
                                        "Madagascar", "Mali", "Mauritania", "Namibia", "Nigeria",
                                        "Norway", "Philippines", "Romania", "Saint Kitts and Nevis",
                                        "Samoa", "Senegal", "Singapore", "Solomon Islands", "Spain",
                                        "Suriname", "Tajikistan", "Turkey", "Uganda",
                                        "United Republic of Tanzania", "Uzbekistan", "Zimbabwe",
                                        "Canada", "Germany", "Mexico", "Netherlands", "Peru",
                                        "United Kingdom", "Viet Nam", "Cambodia", "France", "Indonesia",
                                        "Armenia", "Behamas", "Belgium", "Bolivia", "Denmark", "Egypt",
                                        "Gambia", "Greece", "Guatemala", "Israel", "Kazakhstan", 
                                        "Lao People's Democratic Republic", "Marshall Islands", "Montserrat",
                                        "Nicaragua", "Panama", "Poland", "Republic of Moldova", "Serbia",
                                        "Trinidad and Tobago", "Venezuela (Bolivarian Republic of)",
                                        "Zambia",
                                        "Bolivia (Plurinational State of)", "Benin", "Bangladesh", "Bulgaria"
                                        ))
```

```{r}
mnodef$cases <- c(33,399,14002,723,287,0,0,430,0,0,544,0,311,43196,7371,122757,0,1316,505,53,11835,90,2339,0,214,196,
                  25405,0,0,1215,1172,822,0,313,135,10422,296,4201,1796,6361,9525,525,590,1834,0,451,235,0,
                  51,
                  6963,0,0,5166,1419,89,22282,382,349,346,1786,1702,458,1801,19340,5,0,483,1876,1154,0,17232,
                  486,173,30,1568,270,1433,179,42432,242,267384,22,39,355,426,0)
#mnodef$cases[c(10, 42, 28, 29)] <- c(122757, 271, 6361, 9525)
```

```{r}
###########
## Plot  ##
###########
# create new igraph object
net_degree2 <- graph_from_data_frame(d=medgef, vertices=mnodeup2, directed=T)

# # vertex color based on degree level
#  vcol <- rep("snow2", vcount(net_degree2))     #deebf7 # assigned third degree very light blue to top 101 - 232 countries
#  vcol[223:232] <- "skyblue1"                   #3182bd  #assign first degree dark blue to top ten countries
#  vcol[123:222] <- "slategray1"                 #9ecae1 #assign second degree light blue to top 11-100 countries
#  V(net_degree2)$color <- vcol

# vertex frame color
V(net_degree2)$frame.color <- "black"

# vertex label and size
V(net_degree2)$label <- mnodeup2$Country
V(net_degree2)$label.cex <- 0.5
V(net_degree2)$label.color <- "black"

# Vertex size
V(net_degree2)$size <- rescale(mnodeup2$Influenza2019, to = c(3,10))
  #mnodef$cases/2000
  #round((new_nodes$Degree)/16, 2)

# edge color and size
E(net_degree2)$width <- medgef$Weight
E(net_degree2)$color <- "gray80"
E(net_degree2)$arrow.size <- .2
#E(net_degree)$arrow.mode <- 1

# layout
l <- layout_with_fr(net_degree2)

# plot
par(pin=c(5, 4))
par(mai=c(0.1, 0.1, 0.2, 0.1))
#par(mai=c(0,0,0.1,0.1))
plot(net_degree2, layout = l, vertex.label = V(net_degree2)$label, 
       #ifelse(degree(net_degree2) > 300, V(net_degree2)$label, NA), 
     main="Network Graph with fr layout")

```

```{r}
V(net_degree2)$size
```



```{r}
net_degree2_1 <- graph_from_data_frame(d=medgef, vertices=mnodeup, directed=T)

# # vertex color based on degree level
#  vcol <- rep("snow2", vcount(net_degree2))     #deebf7 # assigned third degree very light blue to top 101 - 232 countries
#  vcol[223:232] <- "skyblue1"                   #3182bd  #assign first degree dark blue to top ten countries
#  vcol[123:222] <- "slategray1"                 #9ecae1 #assign second degree light blue to top 11-100 countries
#  V(net_degree2)$color <- vcol

# vertex frame color
V(net_degree2_1)$frame.color <- "black"

# vertex label and size
V(net_degree2_1)$label <- mnodeup$Country
V(net_degree2_1)$label.cex <- 0.5
V(net_degree2_1)$label.color <- "black"

# Vertex size
V(net_degree2_1)$size <- rescale(mnodeup$Influenza2019, to = c(5, 10))
  #mnodef$cases/2000
  #round((new_nodes$Degree)/16, 2)

# edge color and size
E(net_degree2_1)$width <- medgef$Weight
E(net_degree2_1)$color <- "gray80"
E(net_degree2_1)$arrow.size <- .2
#E(net_degree)$arrow.mode <- 1

# layout
l <- layout_with_fr(net_degree2_1)

# plot
par(mai=c(0,0,0.1,0.1))
plot(net_degree2_1, layout = l, vertex.label = V(net_degree2_1)$label, 
       #ifelse(degree(net_degree2) > 300, V(net_degree2)$label, NA), 
     main="Network Graph with fr layout")

```

```{r}
V(net_degree2_1)$size
```

